### ISSUE TITLE
Can't set wiki while wiki's EditURI start with http:// or https://

### ISSUE THREAD

**Issue by sunny00217wm** [jhsoby/telegram-wikilinksbot#33] opened 2021-09-05 14:32 UTC
see [wikilinksbot.py#L550](https://github.com/jhsoby/telegram-wikilinksbot/blob/master/wikilinksbot.py#L550).

**Comment by jhsoby** [comment] 2021-09-05 20:17
Hi @sunny00217wm. It works as it should for the wikis I've tested with. Could you share which wiki you were trying to set that didn't work?

**Comment by jhsoby** [comment] 2021-09-28 20:43
No reply, can't reproduce, so closing.

**Closed by jhsoby** 2021-09-28 20:43 UTC
